-- Medida final para contar comites/comisiones unicos (sin el valor generico)
-- Requiere tabla importada: Dim_Comites_Comisiones_2026

Num_Comites_Comisiones =
CALCULATE(
	DISTINCTCOUNT(Dim_Comites_Comisiones_2026[comite_comision_nombre]),
	KEEPFILTERS(TREATAS(VALUES(Dim_Comuna[comuna_cod]), Dim_Comites_Comisiones_2026[comuna_cod])),
	KEEPFILTERS(Dim_Comites_Comisiones_2026[comite_comision_nombre] <> "TODOS LOS COMITES Y COMISIONES"),
	KEEPFILTERS(NOT ISBLANK(Dim_Comites_Comisiones_2026[comite_comision_nombre]))
)
