table _Medidas
	lineageTag: b1f93f08-da6d-496c-9a96-414b9e4b2c9e

	measure GenF_Total_Actividades = IF(ISBLANK([GenF_Total_Actividades_VAL]), "N/A", FORMAT([GenF_Total_Actividades_VAL], "#,##0"))
		lineageTag: 6614757e-d0bd-4634-8d56-c2aa4335d7e8

	measure GenF_Total_Actividades_VAL = COUNTROWS(Hecho_Participacion_General)
		isHidden
	measure GenF_Total_Participaciones = IF(ISBLANK([GenF_Total_Participaciones_VAL]), "N/A", FORMAT([GenF_Total_Participaciones_VAL], "#,##0"))
		lineageTag: f4a73d11-1599-437b-aadb-03ab3dd78249

	measure GenF_Total_Participaciones_VAL = SUM(Hecho_Participacion_General[participantes])
		isHidden
	measure Base_Impacto_Indirecto = IF(ISBLANK([Base_Impacto_Indirecto_VAL]), "N/A", FORMAT([Base_Impacto_Indirecto_VAL], "#,##0"))
		lineageTag: c5caf45c-2254-4048-b447-42f5101d37cb

	measure Base_Impacto_Indirecto_VAL = SUM(Hecho_Participacion_General[impacto_indirecto])
		isHidden
	measure Base_Simulacros = IF(ISBLANK([Base_Simulacros_VAL]), "N/A", FORMAT([Base_Simulacros_VAL], "#,##0"))
		lineageTag: abaa5719-dea7-45b1-921e-6f010f9a717e

	measure Base_Simulacros_VAL = COUNTROWS(Hecho_Simulacros)
		isHidden
	measure Base_Simulacros_Personas = IF(ISBLANK([Base_Simulacros_Personas_VAL]), "N/A", FORMAT([Base_Simulacros_Personas_VAL], "#,##0"))
		lineageTag: 29229a13-8c10-445b-91f7-d3c064cc3689

	measure Base_Simulacros_Personas_VAL = SUM(Hecho_Simulacros[personas_participantes])
		isHidden
	measure GenF_Comunitaria_Participaciones = IF(ISBLANK([GenF_Comunitaria_Participaciones_VAL]), "N/A", FORMAT([GenF_Comunitaria_Participaciones_VAL], "#,##0"))
		lineageTag: fe1f0f52-70b2-4aad-8f0c-dc6f51e4b32d

	measure GenF_Comunitaria_Participaciones_VAL = CALCULATE([GenF_Total_Participaciones_VAL], Dim_Seccion[seccion_tablero] = "Comunitaria")
		isHidden
	measure GenF_Educativa_Participaciones = IF(ISBLANK([GenF_Educativa_Participaciones_VAL]), "N/A", FORMAT([GenF_Educativa_Participaciones_VAL], "#,##0"))
		lineageTag: 4f613d19-2ad5-4b4a-9e5d-357e0b40397e

	measure GenF_Educativa_Participaciones_VAL = CALCULATE([GenF_Total_Participaciones_VAL], Dim_Seccion[seccion_tablero] = "Educativa")
		isHidden
	measure GenF_Empresarial_Participaciones = IF(ISBLANK([GenF_Empresarial_Participaciones_VAL]), "N/A", FORMAT([GenF_Empresarial_Participaciones_VAL], "#,##0"))
		lineageTag: 0ce5d729-8bb6-412c-9d47-d97b0e842a34

	measure GenF_Empresarial_Participaciones_VAL = CALCULATE([GenF_Total_Participaciones_VAL], Dim_Seccion[seccion_tablero] = "Empresarial")
		isHidden
	measure GenF_Institucional_Participaciones = IF(ISBLANK([GenF_Institucional_Participaciones_VAL]), "N/A", FORMAT([GenF_Institucional_Participaciones_VAL], "#,##0"))
		lineageTag: 540be670-cc3f-4469-a2ae-afbaa786a0fb

	measure GenF_Institucional_Participaciones_VAL = CALCULATE([GenF_Total_Participaciones_VAL], Dim_Seccion[seccion_tablero] = "Institucional")
		isHidden
	measure Ctl_Referencia_Actividades_OK = IF([GenF_Total_Actividades_VAL] = 3202, "SI", "NO")
		lineageTag: 66e5e4ef-241b-4237-a77c-e2f2a7cb8a77

	measure Ctl_Referencia_Participaciones_OK = IF([GenF_Total_Participaciones_VAL] = 111694, "SI", "NO")
		lineageTag: c4e08b5a-a876-4d3d-9da3-ba38de5736aa

	measure Articulacion_Institucional = IF(ISBLANK([Articulacion_Institucional_VAL]), "N/A", FORMAT([Articulacion_Institucional_VAL], "#,##0"))
		lineageTag: f8d79608-efd0-47a8-9a9f-f1d302047240

	measure Articulacion_Institucional_VAL = CALCULATE(COUNTROWS(Hecho_Participacion_General), Hecho_Participacion_General[bloque_institucional] = "Articulacion Institucional")
		isHidden
	measure Mesas_Interinstitucionalidad = IF(ISBLANK([Mesas_Interinstitucionalidad_VAL]), "N/A", FORMAT([Mesas_Interinstitucionalidad_VAL], "#,##0"))
		lineageTag: 354577c7-269a-4976-9e3a-d72228edba27

	measure Mesas_Interinstitucionalidad_VAL = CALCULATE(COUNTROWS(Hecho_Participacion_General), Hecho_Participacion_General[bloque_institucional] = "Mesas Interinstitucionalidad en el territorio")
		isHidden
	measure Acciones_Conjuntas = IF(ISBLANK([Acciones_Conjuntas_VAL]), "N/A", FORMAT([Acciones_Conjuntas_VAL], "#,##0"))
		lineageTag: 33041afa-6a0a-4521-8f7d-76c53f61ef5a

	measure Acciones_Conjuntas_VAL = CALCULATE(COUNTROWS(Hecho_Participacion_General), Hecho_Participacion_General[bloque_institucional] = "Acciones Conjuntas")
		isHidden
	measure Simulacros_Registrados_Total = IF(ISBLANK([Simulacros_Registrados_Total_VAL]), "N/A", FORMAT([Simulacros_Registrados_Total_VAL], "#,##0"))
		lineageTag: 79e5c3d2-1dd5-4d17-ab30-c683626542a7

	measure Simulacros_Registrados_Total_VAL = COUNTROWS(Hecho_Simulacros)
		isHidden
	measure Cobertura_Total = IF(ISBLANK([Cobertura_Total_VAL]), "N/A", FORMAT([Cobertura_Total_VAL], "#,##0"))
		lineageTag: f76a7b9f-79e9-487d-98c9-1d1ace0fe697

	measure Cobertura_Total_VAL = [GenF_Total_Participaciones_VAL] + [Base_Impacto_Indirecto_VAL]
		isHidden
	measure Participaciones_Institucionales = IF(ISBLANK([Participaciones_Institucionales_VAL]), "N/A", FORMAT([Participaciones_Institucionales_VAL], "#,##0"))
		lineageTag: de75b43e-83d3-463d-8254-397bec7780f9

	measure Participaciones_Institucionales_VAL = CALCULATE(SUM(Hecho_Participacion_General[participantes]), Hecho_Participacion_General[seccion_tablero] = "Institucional")
		isHidden
	measure Participantes_Articulacion = IF(ISBLANK([Participantes_Articulacion_VAL]), "N/A", FORMAT([Participantes_Articulacion_VAL], "#,##0"))
		displayFolder: Institucional
		lineageTag: d4b18fac-b741-4997-bdd8-e1e9775e2ca3

	measure Participantes_Articulacion_VAL = CALCULATE(SUM(Hecho_Participacion_General[participantes]), Dim_Seccion[seccion_tablero] = "Institucional", Hecho_Participacion_General[bloque_institucional] = "Articulacion Institucional")
		isHidden
	measure Participantes_Mesas = IF(ISBLANK([Participantes_Mesas_VAL]), "N/A", FORMAT([Participantes_Mesas_VAL], "#,##0"))
		displayFolder: Institucional
		lineageTag: 7d46477a-c6f5-4db1-8ecf-32aa0a0a232c

	measure Participantes_Mesas_VAL = CALCULATE(SUM(Hecho_Participacion_General[participantes]), Dim_Seccion[seccion_tablero] = "Institucional", Hecho_Participacion_General[bloque_institucional] = "Mesas Interinstitucionalidad en el territorio")
		isHidden
	measure Participantes_Acciones_Conjuntas = IF(ISBLANK([Participantes_Acciones_Conjuntas_VAL]), "N/A", FORMAT([Participantes_Acciones_Conjuntas_VAL], "#,##0"))
		displayFolder: Institucional
		lineageTag: 2e33dbca-50dc-46e1-83bd-024f083b0cb0

	measure Participantes_Acciones_Conjuntas_VAL = CALCULATE(SUM(Hecho_Participacion_General[participantes]), Dim_Seccion[seccion_tablero] = "Institucional", Hecho_Participacion_General[bloque_institucional] = "Acciones Conjuntas")
		isHidden
	measure Entidades_en_Simulacros = IF(ISBLANK([Entidades_en_Simulacros_VAL]), "N/A", FORMAT([Entidades_en_Simulacros_VAL], "#,##0"))
		lineageTag: 20def80c-b469-4bd3-8812-d7b1adbff52c

	measure Entidades_en_Simulacros_VAL = DISTINCTCOUNT(Hecho_Simulacros[nombre_entidad])
		isHidden
	measure Simulacros_Institucionales = IF(ISBLANK([Simulacros_Institucionales_VAL]), "N/A", FORMAT([Simulacros_Institucionales_VAL], "#,##0"))
		lineageTag: 751bf8b1-5e52-4293-8c32-205a5d82e6b4

	measure Simulacros_Institucionales_VAL = CALCULATE(COUNTROWS(Hecho_Simulacros), Hecho_Simulacros[sector_tablero] = "Institucional")
		isHidden
	measure Actividades_Comites = IF(ISBLANK([Actividades_Comites_VAL]), "N/A", FORMAT([Actividades_Comites_VAL], "#,##0"))
		lineageTag: f67d4e2d-7de4-47b6-8a04-41c26207bf0f

	measure Actividades_Comites_VAL = CALCULATE(COUNTROWS(Hecho_Participacion_General), Hecho_Participacion_General[bloque_comunidad] = "Comisiones y comites")
		isHidden
	measure Actividades_Semilleros = IF(ISBLANK([Actividades_Semilleros_VAL]), "N/A", FORMAT([Actividades_Semilleros_VAL], "#,##0"))
		lineageTag: 19a0b33d-a088-466c-b2bf-f2f162fd4404

	measure Actividades_Semilleros_VAL = CALCULATE(COUNTROWS(Hecho_Participacion_General), Hecho_Participacion_General[bloque_comunidad] = "Semilleros")
		isHidden
	measure Actividades_SATC = IF(ISBLANK([Actividades_SATC_VAL]), "N/A", FORMAT([Actividades_SATC_VAL], "#,##0"))
		lineageTag: b8aa7e02-4ac3-4ceb-a016-ec821001c303

	measure Actividades_SATC_VAL = CALCULATE(COUNTROWS(Hecho_Participacion_General), Hecho_Participacion_General[bloque_comunidad] = "SAT-C")
		isHidden
	measure Actividades_HogarSeguro = IF(ISBLANK([Actividades_HogarSeguro_VAL]), "N/A", FORMAT([Actividades_HogarSeguro_VAL], "#,##0"))
		lineageTag: cc83bd04-a630-48ab-8329-a807a61203c1

	measure Actividades_HogarSeguro_VAL = CALCULATE(COUNTROWS(Hecho_Participacion_General), Hecho_Participacion_General[bloque_comunidad] = "Hogares - Planes Familiares/Hogar Seguro")
		isHidden
	measure Actividades_Comunidad_Otros = IF(ISBLANK([Actividades_Comunidad_Otros_VAL]), "N/A", FORMAT([Actividades_Comunidad_Otros_VAL], "#,##0"))
		lineageTag: 43c59168-859a-4b58-9cc0-c044fcef4a69

	measure Actividades_Comunidad_Otros_VAL = CALCULATE(COUNTROWS(Hecho_Participacion_General), Hecho_Participacion_General[bloque_comunidad] = "Otros Procesos Organizativos")
		isHidden
	measure Participantes_Comites = IF(ISBLANK([Participantes_Comites_VAL]), "N/A", FORMAT([Participantes_Comites_VAL], "#,##0"))
		lineageTag: 43e33c67-88b8-458f-9791-6e409f9eb5c2

	measure Participantes_Comites_VAL = CALCULATE(SUM(Hecho_Participacion_General[participantes]), Hecho_Participacion_General[bloque_comunidad] = "Comisiones y comites")
		isHidden
	measure Participantes_Semilleros = IF(ISBLANK([Participantes_Semilleros_VAL]), "N/A", FORMAT([Participantes_Semilleros_VAL], "#,##0"))
		lineageTag: 50e3c726-6d75-4c7e-b22a-0f359d878311

	measure Participantes_Semilleros_VAL = CALCULATE(SUM(Hecho_Participacion_General[participantes]), Hecho_Participacion_General[bloque_comunidad] = "Semilleros")
		isHidden
	measure Participantes_SATC = IF(ISBLANK([Participantes_SATC_VAL]), "N/A", FORMAT([Participantes_SATC_VAL], "#,##0"))
		lineageTag: 0f80ecb4-8222-4076-bb22-d2d1302f1d66

	measure Participantes_SATC_VAL = CALCULATE(SUM(Hecho_Participacion_General[participantes]), Hecho_Participacion_General[bloque_comunidad] = "SAT-C")
		isHidden
	measure Participantes_HogarSeguro = IF(ISBLANK([Participantes_HogarSeguro_VAL]), "N/A", FORMAT([Participantes_HogarSeguro_VAL], "#,##0"))
		lineageTag: 739bcabd-2daf-41ed-a718-c7179cfebe39

	measure Participantes_HogarSeguro_VAL = CALCULATE(SUM(Hecho_Participacion_General[participantes]), Hecho_Participacion_General[bloque_comunidad] = "Hogares - Planes Familiares/Hogar Seguro")
		isHidden
	measure Impacto_Indirecto_Comunidad = IF(ISBLANK([Impacto_Indirecto_Comunidad_VAL]), "N/A", FORMAT([Impacto_Indirecto_Comunidad_VAL], "#,##0"))
		lineageTag: b7102063-6a86-462f-b8bd-4256da0895cb

	measure Impacto_Indirecto_Comunidad_VAL = CALCULATE(SUM(Hecho_Participacion_General[impacto_indirecto]), Hecho_Participacion_General[seccion_tablero] = "Comunitaria")
		isHidden
	measure Actividades_PrimeraInfancia = IF(ISBLANK([Actividades_PrimeraInfancia_VAL]), "N/A", FORMAT([Actividades_PrimeraInfancia_VAL], "#,##0"))
		lineageTag: e5651a48-83ea-4d91-ade3-227482a7e56f

	measure Actividades_PrimeraInfancia_VAL = CALCULATE(COUNTROWS(Hecho_Participacion_General), Hecho_Participacion_General[bloque_educacion] = "Instituciones Primera Infancia")
		isHidden
	measure Actividades_BasicaMedia = IF(ISBLANK([Actividades_BasicaMedia_VAL]), "N/A", FORMAT([Actividades_BasicaMedia_VAL], "#,##0"))
		lineageTag: dcec11f6-f3f1-4e1b-a38e-98d23355483d

	measure Actividades_BasicaMedia_VAL = CALCULATE(COUNTROWS(Hecho_Participacion_General), Hecho_Participacion_General[bloque_educacion] = "Basica Media")
		isHidden
	measure Actividades_Superior = IF(ISBLANK([Actividades_Superior_VAL]), "N/A", FORMAT([Actividades_Superior_VAL], "#,##0"))
		lineageTag: f834f68c-4e68-4b5e-b5bd-04748dceb94e

	measure Actividades_Superior_VAL = CALCULATE(COUNTROWS(Hecho_Participacion_General), Hecho_Participacion_General[bloque_educacion] = "Educacion Superior")
		isHidden
	measure Participantes_PrimeraInfancia = IF(ISBLANK([Participantes_PrimeraInfancia_VAL]), "N/A", FORMAT([Participantes_PrimeraInfancia_VAL], "#,##0"))
		lineageTag: d3b27293-ba6e-49f4-a6e7-d44f0c8333ba

	measure Participantes_PrimeraInfancia_VAL = CALCULATE(SUM(Hecho_Participacion_General[participantes]), Hecho_Participacion_General[bloque_educacion] = "Instituciones Primera Infancia")
		isHidden
	measure Participantes_BasicaMedia = IF(ISBLANK([Participantes_BasicaMedia_VAL]), "N/A", FORMAT([Participantes_BasicaMedia_VAL], "#,##0"))
		lineageTag: f2483028-99c7-4528-8ca9-75158298e691

	measure Participantes_BasicaMedia_VAL = CALCULATE(SUM(Hecho_Participacion_General[participantes]), Hecho_Participacion_General[bloque_educacion] = "Basica Media")
		isHidden
	measure Participantes_Superior = IF(ISBLANK([Participantes_Superior_VAL]), "N/A", FORMAT([Participantes_Superior_VAL], "#,##0"))
		lineageTag: c0aabfa6-13d8-4776-ac0b-d2e77da5acd1

	measure Participantes_Superior_VAL = CALCULATE(SUM(Hecho_Participacion_General[participantes]), Hecho_Participacion_General[bloque_educacion] = "Educacion Superior")
		isHidden
	measure Impacto_Indirecto_Educacion = IF(ISBLANK([Impacto_Indirecto_Educacion_VAL]), "N/A", FORMAT([Impacto_Indirecto_Educacion_VAL], "#,##0"))
		lineageTag: 1305b9c1-ab4d-40cd-b6c5-e373e4560b35

	measure Impacto_Indirecto_Educacion_VAL = CALCULATE(SUM(Hecho_Participacion_General[impacto_indirecto]), Hecho_Participacion_General[seccion_tablero] = "Educativa")
		isHidden
	measure Actividades_CAM = IF(ISBLANK([Actividades_CAM_VAL]), "N/A", FORMAT([Actividades_CAM_VAL], "#,##0"))
		displayFolder: Empresarial
		lineageTag: 231c3af5-e1d8-4945-ba9a-1db76c247351

	measure Actividades_CAM_VAL = MAX(CAM_Control[cam_activos_total])
		isHidden
	measure Actividades_PropiedadHorizontal = IF(ISBLANK([Actividades_PropiedadHorizontal_VAL]), "N/A", FORMAT([Actividades_PropiedadHorizontal_VAL], "#,##0"))
		displayFolder: Empresarial
		lineageTag: 41af3518-bf13-4104-a322-a836bfe34824

	measure Actividades_PropiedadHorizontal_VAL = CALCULATE(COUNTROWS(Hecho_Participacion_General), Dim_Seccion[seccion_tablero] = "Empresarial", Hecho_Participacion_General[bloque_empresarial] = "Propiedades Horizontales")
		isHidden
	measure Actividades_Empresa = IF(ISBLANK([Actividades_Empresa_VAL]), "N/A", FORMAT([Actividades_Empresa_VAL], "#,##0"))
		displayFolder: Empresarial
		lineageTag: 2cf53097-1300-4f94-bd72-f2b411e62b8a

	measure Actividades_Empresa_VAL = MAX(CAM_Control[empresas_unicas_global])
		isHidden
	measure Actividades_Simulacro_Empresarial = IF(ISBLANK([Actividades_Simulacro_Empresarial_VAL]), "N/A", FORMAT([Actividades_Simulacro_Empresarial_VAL], "#,##0"))
		lineageTag: 3176b2da-dc7c-4f5e-a6be-daec099cfa8e

	measure Actividades_Simulacro_Empresarial_VAL = CALCULATE(COUNTROWS(Hecho_Simulacros), Hecho_Simulacros[sector_tablero] = "Empresarial")
		isHidden
	measure Participantes_CAM = IF(ISBLANK([Participantes_CAM_VAL]), "N/A", FORMAT([Participantes_CAM_VAL], "#,##0"))
		displayFolder: Empresarial
		lineageTag: 0e2d7a9d-7b55-4d3b-8c5f-4f2f2d9c7f71

	measure Participantes_CAM_VAL = CALCULATE(SUM(Hecho_Participacion_General[participantes]), Dim_Seccion[seccion_tablero] = "Empresarial", Hecho_Participacion_General[bloque_empresarial] = "CAM")
		isHidden
	measure Participantes_PropiedadHorizontal = IF(ISBLANK([Participantes_PropiedadHorizontal_VAL]), "N/A", FORMAT([Participantes_PropiedadHorizontal_VAL], "#,##0"))
		displayFolder: Empresarial
		lineageTag: 10ce6574-d587-46e5-8ccf-fc41eb77fa77

	measure Participantes_PropiedadHorizontal_VAL = CALCULATE(SUM(Hecho_Participacion_General[participantes]), Dim_Seccion[seccion_tablero] = "Empresarial", Hecho_Participacion_General[bloque_empresarial] = "Propiedades Horizontales")
		isHidden
	measure Participantes_Empresa = IF(ISBLANK([Participantes_Empresa_VAL]), "N/A", FORMAT([Participantes_Empresa_VAL], "#,##0"))
		displayFolder: Empresarial
		lineageTag: 13242fbd-7302-4ffe-863d-c5bff7090dce

	measure Participantes_Empresa_VAL = CALCULATE(SUM(Hecho_Participacion_General[participantes]), Dim_Seccion[seccion_tablero] = "Empresarial", Hecho_Participacion_General[bloque_empresarial] = "Empresas")
		isHidden
	measure Simulacros_Empresariales = IF(ISBLANK([Simulacros_Empresariales_VAL]), "N/A", FORMAT([Simulacros_Empresariales_VAL], "#,##0"))
		lineageTag: f0db8d82-9ac2-454f-a476-356c5ae19267

	measure Simulacros_Empresariales_VAL = CALCULATE(COUNTROWS(Hecho_Simulacros), Hecho_Simulacros[sector_tablero] = "Empresarial")
		isHidden
	measure Participantes_Simulacros_Empresariales = IF(ISBLANK([Participantes_Simulacros_Empresariales_VAL]), "N/A", FORMAT([Participantes_Simulacros_Empresariales_VAL], "#,##0"))
		lineageTag: 4b14988e-9b11-4ad7-8d41-2eb00c051666

	measure Participantes_Simulacros_Empresariales_VAL = CALCULATE(SUM(Hecho_Simulacros[personas_participantes]), Hecho_Simulacros[sector_tablero] = "Empresarial")
		isHidden
	measure Dem_PrimeraInfancia = IF(ISBLANK([Dem_PrimeraInfancia_VAL]), "N/A", FORMAT([Dem_PrimeraInfancia_VAL], "#,##0"))
		lineageTag: 9da52db0-2e38-4cfb-b602-8594cd6e5bbe

	measure Dem_PrimeraInfancia_VAL = SUM(Hecho_Participacion_General[pri_infanc])
		isHidden
	measure Dem_NinoAdolescente = IF(ISBLANK([Dem_NinoAdolescente_VAL]), "N/A", FORMAT([Dem_NinoAdolescente_VAL], "#,##0"))
		lineageTag: 920e4f9f-36b4-4cb4-ac64-805f14a8492c

	measure Dem_NinoAdolescente_VAL = SUM(Hecho_Participacion_General[nino_adole])
		isHidden
	measure Dem_Juventud = IF(ISBLANK([Dem_Juventud_VAL]), "N/A", FORMAT([Dem_Juventud_VAL], "#,##0"))
		lineageTag: 394cc7de-35b9-43fa-a59c-0c76f644fc93

	measure Dem_Juventud_VAL = SUM(Hecho_Participacion_General[juventud])
		isHidden
	measure Dem_Adulto = IF(ISBLANK([Dem_Adulto_VAL]), "N/A", FORMAT([Dem_Adulto_VAL], "#,##0"))
		lineageTag: 8582bc90-0ab7-4cc1-b5e5-1a78d84052e6

	measure Dem_Adulto_VAL = SUM(Hecho_Participacion_General[adulto])
		isHidden
	measure Dem_AdultoMayor = IF(ISBLANK([Dem_AdultoMayor_VAL]), "N/A", FORMAT([Dem_AdultoMayor_VAL], "#,##0"))
		lineageTag: 60939ee8-e080-44ea-93c8-757cef4a3a4f

	measure Dem_AdultoMayor_VAL = SUM(Hecho_Participacion_General[adulto_may])
		isHidden
	measure Dem_Discapacidad = IF(ISBLANK([Dem_Discapacidad_VAL]), "N/A", FORMAT([Dem_Discapacidad_VAL], "#,##0"))
		lineageTag: d43641e4-7545-414d-8ca5-76261f5d95de

	measure Dem_Discapacidad_VAL = SUM(Hecho_Participacion_General[discapacid])
		isHidden
	measure Dem_Afrodescendiente = IF(ISBLANK([Dem_Afrodescendiente_VAL]), "N/A", FORMAT([Dem_Afrodescendiente_VAL], "#,##0"))
		lineageTag: a3d769fe-a24f-4fd4-9262-6b281f9fbf5b

	measure Dem_Afrodescendiente_VAL = SUM(Hecho_Participacion_General[afrodescen])
		isHidden
	measure Dem_Campesino = IF(ISBLANK([Dem_Campesino_VAL]), "N/A", FORMAT([Dem_Campesino_VAL], "#,##0"))
		lineageTag: 2aeaf2db-8765-4ef5-ad98-b5925ccd198f

	measure Dem_Campesino_VAL = SUM(Hecho_Participacion_General[campesino])
		isHidden
	measure Dem_Indigena = IF(ISBLANK([Dem_Indigena_VAL]), "N/A", FORMAT([Dem_Indigena_VAL], "#,##0"))
		lineageTag: 66b70248-7a91-4fcb-a489-07e8ae90da7b

	measure Dem_Indigena_VAL = SUM(Hecho_Participacion_General[pob_indige])
		isHidden
	measure Dem_Rom = IF(ISBLANK([Dem_Rom_VAL]), "N/A", FORMAT([Dem_Rom_VAL], "#,##0"))
		lineageTag: 612b2322-60be-4b3f-af59-68e950eb9bdb

	measure Dem_Rom_VAL = SUM(Hecho_Participacion_General[pob_rom])
		isHidden
	measure Dem_Victimas = IF(ISBLANK([Dem_Victimas_VAL]), "N/A", FORMAT([Dem_Victimas_VAL], "#,##0"))
		lineageTag: 71bf6166-d60d-4a8e-ab57-7a5ba9bf3756

	measure Dem_Victimas_VAL = SUM(Hecho_Participacion_General[pob_victim])
		isHidden
	measure Dem_Migrante = IF(ISBLANK([Dem_Migrante_VAL]), "N/A", FORMAT([Dem_Migrante_VAL], "#,##0"))
		lineageTag: 1707e1be-3011-4310-b2e9-af0a438d062d

	measure Dem_Migrante_VAL = SUM(Hecho_Participacion_General[pob_migran])
		isHidden
	measure Dem_LGTBI = IF(ISBLANK([Dem_LGTBI_VAL]), "N/A", FORMAT([Dem_LGTBI_VAL], "#,##0"))
		lineageTag: dfd31b1e-97d8-4b05-bc0c-2fae96cf94ac

	measure Dem_LGTBI_VAL = SUM(Hecho_Participacion_General[pob_lgtbi])
		isHidden
	measure Total_Dem_Valor = IF(ISBLANK([Total_Dem_Valor_VAL]), "N/A", FORMAT([Total_Dem_Valor_VAL], "#,##0"))
		lineageTag: 16207a98-d6c0-4f15-9718-6077d02f521e

	measure Total_Dem_Valor_VAL = SUM(Hecho_Demografia[valor])
		isHidden
	/// Numero de comites y comisiones distintos (excluye valor generico TODOS LOS COMITES Y COMISIONES).
	measure Num_Comites_Comisiones = IF(ISBLANK([Num_Comites_Comisiones_VAL]), "N/A", FORMAT([Num_Comites_Comisiones_VAL], "#,##0"))
		formatString: 0
		lineageTag: 78a5d1f2-0699-4be0-aeb9-d8984308c586

	measure Num_Comites_Comisiones_VAL = DISTINCTCOUNT(Dim_Comites_Comisiones_2026[comite_comision_nombre])
		isHidden
	/// Etiqueta año-mes para eje de tendencia (ej: 2024-07)
	measure Eje_AnioMes = FORMAT(MIN(Dim_Fecha[anio]), "0000") & "-" & FORMAT(MIN(Dim_Fecha[mes_num]), "00")
		lineageTag: dfb22f1c-7009-4afd-8c24-271ccc1e2e34

	/// Participaciones directas + personas simulacros + impacto indirecto
	measure Cobertura_Global = IF(ISBLANK([Cobertura_Global_VAL]), "N/A", FORMAT([Cobertura_Global_VAL], "#,##0"))

	measure Cobertura_Global_VAL = 
			SUMX(
			    VALUES(Hecho_Participacion_General[seccion_tablero]),
			    [GenF_Total_Participaciones_VAL]
			) + [Base_Simulacros_Personas_VAL]
		formatString: #,##0
		lineageTag: 3100b730-cfb0-48d9-ab4d-6cfc5b80a8a4
		isHidden
	measure GenF_Empresarial_Actividades = IF(ISBLANK([GenF_Empresarial_Actividades_VAL]), "N/A", FORMAT([GenF_Empresarial_Actividades_VAL], "#,##0"))
		displayFolder: Empresarial
		lineageTag: 659177d1-226e-472a-acfe-a4f23df02515

	measure GenF_Empresarial_Actividades_VAL = CALCULATE([GenF_Total_Actividades_VAL], Dim_Seccion[seccion_tablero] = "Empresarial")
		isHidden
	measure GenF_Empresarial_Impacto = IF(ISBLANK([GenF_Empresarial_Impacto_VAL]), "N/A", FORMAT([GenF_Empresarial_Impacto_VAL], "#,##0"))
		displayFolder: Empresarial
		lineageTag: ea76f394-ccd2-43ee-be67-f87335b723e2

	measure GenF_Empresarial_Impacto_VAL = CALCULATE([Base_Impacto_Indirecto_VAL], Dim_Seccion[seccion_tablero] = "Empresarial")
		isHidden
	measure Actividades_PlanesAyudaMutua = IF(ISBLANK([Actividades_PlanesAyudaMutua_VAL]), "N/A", FORMAT([Actividades_PlanesAyudaMutua_VAL], "#,##0"))
		displayFolder: Empresarial
		lineageTag: 88802f32-9f2e-440a-b554-cd7bc83d5951

	measure Actividades_PlanesAyudaMutua_VAL = CALCULATE(COUNTROWS(Hecho_Participacion_General), Dim_Seccion[seccion_tablero] = "Empresarial", Hecho_Participacion_General[bloque_empresarial] = "Planes de ayuda mutua/Acuerdo de voluntades")
		isHidden
	measure Participantes_PlanesAyudaMutua = IF(ISBLANK([Participantes_PlanesAyudaMutua_VAL]), "N/A", FORMAT([Participantes_PlanesAyudaMutua_VAL], "#,##0"))
		displayFolder: Empresarial
		lineageTag: 09e3fbcb-d86a-4084-a9cd-692770a21251

	measure Participantes_PlanesAyudaMutua_VAL = CALCULATE(SUM(Hecho_Participacion_General[participantes]), Dim_Seccion[seccion_tablero] = "Empresarial", Hecho_Participacion_General[bloque_empresarial] = "Planes de ayuda mutua/Acuerdo de voluntades")
		isHidden
	measure Sim_Empresarial_Registros = IF(ISBLANK([Sim_Empresarial_Registros_VAL]), "N/A", FORMAT([Sim_Empresarial_Registros_VAL], "#,##0"))
		displayFolder: Empresarial
		lineageTag: a5b9c71d-a691-42ae-8c74-c374e2681461

	measure Sim_Empresarial_Registros_VAL = CALCULATE([Base_Simulacros_VAL], Hecho_Simulacros[sector_tablero] = "Empresarial")
		isHidden
	measure Sim_Empresarial_Personas = IF(ISBLANK([Sim_Empresarial_Personas_VAL]), "N/A", FORMAT([Sim_Empresarial_Personas_VAL], "#,##0"))
		displayFolder: Empresarial
		lineageTag: d98080ed-293b-419e-be55-584bba6c9e80

	measure Sim_Empresarial_Personas_VAL = CALCULATE([Base_Simulacros_Personas_VAL], Hecho_Simulacros[sector_tablero] = "Empresarial")
		isHidden
	measure GenF_Institucional_Impacto = IF(ISBLANK([GenF_Institucional_Impacto_VAL]), "N/A", FORMAT([GenF_Institucional_Impacto_VAL], "#,##0"))
		displayFolder: Institucional
		lineageTag: 5d63581a-896e-4862-84d7-e178756153a5

	measure GenF_Institucional_Impacto_VAL = CALCULATE([Base_Impacto_Indirecto_VAL], Dim_Seccion[seccion_tablero] = "Institucional")
		isHidden
	measure Actividades_Mesas = IF(ISBLANK([Actividades_Mesas_VAL]), "N/A", FORMAT([Actividades_Mesas_VAL], "#,##0"))
		displayFolder: Institucional
		lineageTag: 39a99364-1740-48f5-bc85-eebd1b113a4e

	measure Actividades_Mesas_VAL = CALCULATE(COUNTROWS(Hecho_Participacion_General), Dim_Seccion[seccion_tablero] = "Institucional", Hecho_Participacion_General[bloque_institucional] = "Mesas Interinstitucionalidad en el territorio")
		isHidden
	measure Actividades_AccionesConjuntas = IF(ISBLANK([Actividades_AccionesConjuntas_VAL]), "N/A", FORMAT([Actividades_AccionesConjuntas_VAL], "#,##0"))
		displayFolder: Institucional
		lineageTag: 062c4d0c-a494-44fb-9fe4-f64dfa477489

	measure Actividades_AccionesConjuntas_VAL = CALCULATE(COUNTROWS(Hecho_Participacion_General), Dim_Seccion[seccion_tablero] = "Institucional", Hecho_Participacion_General[bloque_institucional] = "Acciones Conjuntas")
		isHidden
	measure Actividades_ArticulacionInstitucional = IF(ISBLANK([Actividades_ArticulacionInstitucional_VAL]), "N/A", FORMAT([Actividades_ArticulacionInstitucional_VAL], "#,##0"))
		displayFolder: Institucional
		lineageTag: 671188ab-cf56-4ce0-a3d4-5057d2353b27

	measure Actividades_ArticulacionInstitucional_VAL = CALCULATE(COUNTROWS(Hecho_Participacion_General), Dim_Seccion[seccion_tablero] = "Institucional", Hecho_Participacion_General[bloque_institucional] = "Articulacion Institucional")
		isHidden
	measure GenF_Institucional_Actividades = IF(ISBLANK([GenF_Institucional_Actividades_VAL]), "N/A", FORMAT([GenF_Institucional_Actividades_VAL], "#,##0"))
		displayFolder: Institucional
		lineageTag: 71171d20-7181-4dda-a581-9dd5d1791aac

	measure GenF_Institucional_Actividades_VAL = CALCULATE([GenF_Total_Actividades_VAL], Dim_Seccion[seccion_tablero] = "Institucional")
		isHidden
	/// Número de instituciones educativas únicas con las que se ha trabajado
	measure GenF_Edu_Instituciones_Unicas = IF(ISBLANK([GenF_Edu_Instituciones_Unicas_VAL]), "N/A", FORMAT([GenF_Edu_Instituciones_Unicas_VAL], "#,##0"))

	measure GenF_Edu_Instituciones_Unicas_VAL = 
			VAR _ComunasSeleccionadas = VALUES(Dim_Comuna[comuna_cod])
			RETURN
			    CALCULATE(
			        DISTINCTCOUNT(Hecho_Participacion_General[institucion_educativa_norm]),
			        Hecho_Participacion_General[seccion_tablero] = "Educativa",
			        NOT(ISBLANK(Hecho_Participacion_General[institucion_educativa_norm])),
			        REMOVEFILTERS(Hecho_Participacion_General[comuna_cod]),
			        KEEPFILTERS(TREATAS(_ComunasSeleccionadas, Hecho_Participacion_General[comuna_institucion_educativa_cod]))
			    )
		displayFolder: Educativa/Instituciones
		lineageTag: a22a77ec-46e0-44d9-b540-8d2da138910b
		isHidden
	/// Cantidad de actividades de acompanamiento a planes escolares de gestion del riesgo en educativa; ignora filtros estructurales de seccion/instancia institucional para evitar blancos
	measure Edu_Acomp_PlanesEscolares_GRD = IF(ISBLANK([Edu_Acomp_PlanesEscolares_GRD_VAL]), "N/A", FORMAT([Edu_Acomp_PlanesEscolares_GRD_VAL], "#,##0"))

	measure Edu_Acomp_PlanesEscolares_GRD_VAL = 
			VAR _valor =
			    CALCULATE(
			        COUNTROWS(Hecho_Participacion_General),
			        REMOVEFILTERS(Dim_Seccion[seccion_tablero]),
			        REMOVEFILTERS(Dim_Instancia[instancia]),
			        REMOVEFILTERS(Hecho_Participacion_General[seccion_tablero]),
			        REMOVEFILTERS(Hecho_Participacion_General[instancia]),
			        REMOVEFILTERS(Hecho_Participacion_General[ambito_institucional]),
			        REMOVEFILTERS(Hecho_Participacion_General[grupo_ambito_comparacion]),
			        REMOVEFILTERS(Hecho_Participacion_General[bloque_institucional]),
			        REMOVEFILTERS(Hecho_Participacion_General[subbloque_institucional]),
			        Hecho_Participacion_General[seccion_tablero] = "Educativa",
			        CONTAINSSTRING(LOWER(COALESCE(Hecho_Participacion_General[actividad_educacion], "")), "plan escolar"),
			        CONTAINSSTRING(LOWER(COALESCE(Hecho_Participacion_General[actividad_educacion], "")), "acompa")
			    )
			RETURN
			    COALESCE(_valor, 0)
		displayFolder: Educativa
		lineageTag: 113de143-b958-4f09-bce4-6bd6131c4315
		isHidden
	measure GenF_Edu_Instituciones_Media = IF(ISBLANK([GenF_Edu_Instituciones_Media_VAL]), "N/A", FORMAT([GenF_Edu_Instituciones_Media_VAL], "#,##0"))

	measure GenF_Edu_Instituciones_Media_VAL = 
			VAR _ComunasSeleccionadas = VALUES(Dim_Comuna[comuna_cod])
			RETURN
			    CALCULATE(
			        DISTINCTCOUNT(Hecho_Participacion_General[institucion_educativa_norm]),
			        Hecho_Participacion_General[seccion_tablero] = "Educativa",
			        Hecho_Participacion_General[bloque_educacion] = "Basica Media",
			        NOT(ISBLANK(Hecho_Participacion_General[institucion_educativa_norm])),
			        REMOVEFILTERS(Hecho_Participacion_General[comuna_cod]),
			        KEEPFILTERS(TREATAS(_ComunasSeleccionadas, Hecho_Participacion_General[comuna_institucion_educativa_cod]))
			    )
		displayFolder: Educativa/Instituciones
		lineageTag: a08a43f2-d861-44b0-a10a-2c3614f52d1f
		isHidden
	measure GenF_Edu_Instituciones_Superior = IF(ISBLANK([GenF_Edu_Instituciones_Superior_VAL]), "N/A", FORMAT([GenF_Edu_Instituciones_Superior_VAL], "#,##0"))

	measure GenF_Edu_Instituciones_Superior_VAL = 
			VAR _ComunasSeleccionadas = VALUES(Dim_Comuna[comuna_cod])
			RETURN
			    CALCULATE(
			        DISTINCTCOUNT(Hecho_Participacion_General[institucion_educativa_norm]),
			        Hecho_Participacion_General[seccion_tablero] = "Educativa",
			        Hecho_Participacion_General[bloque_educacion] = "Educacion Superior",
			        NOT(ISBLANK(Hecho_Participacion_General[institucion_educativa_norm])),
			        REMOVEFILTERS(Hecho_Participacion_General[comuna_cod]),
			        KEEPFILTERS(TREATAS(_ComunasSeleccionadas, Hecho_Participacion_General[comuna_institucion_educativa_cod]))
			    )
		displayFolder: Educativa/Instituciones
		lineageTag: 92b1311b-3b1c-4ee9-9065-183914c3ba0b
		isHidden
	measure GenF_Edu_Instituciones_PrimeraInfancia = IF(ISBLANK([GenF_Edu_Instituciones_PrimeraInfancia_VAL]), "N/A", FORMAT([GenF_Edu_Instituciones_PrimeraInfancia_VAL], "#,##0"))

	measure GenF_Edu_Instituciones_PrimeraInfancia_VAL = 
			VAR _ComunasSeleccionadas = VALUES(Dim_Comuna[comuna_cod])
			RETURN
			    CALCULATE(
			        DISTINCTCOUNT(Hecho_Participacion_General[institucion_educativa_norm]),
			        Hecho_Participacion_General[seccion_tablero] = "Educativa",
			        Hecho_Participacion_General[bloque_educacion] = "Instituciones Primera Infancia",
			        NOT(ISBLANK(Hecho_Participacion_General[institucion_educativa_norm])),
			        REMOVEFILTERS(Hecho_Participacion_General[comuna_cod]),
			        KEEPFILTERS(TREATAS(_ComunasSeleccionadas, Hecho_Participacion_General[comuna_institucion_educativa_cod]))
			    )
		displayFolder: Educativa/Instituciones
		lineageTag: 16af2ef7-f148-4fe8-9edd-4957c65cda1a
		isHidden
	column Id
		isHidden
		lineageTag: ee6ca3f0-fc85-4bda-a77b-d890b9489803
		summarizeBy: none
		isNameInferred
		sourceColumn: [Id]

	partition _Medidas = calculated
		mode: import
		source = DATATABLE("Id", INTEGER, {{1}})

