table Dim_SATC_Relaciones
	lineageTag: 6329e5c1-d29b-4e8a-bf4d-7fb0bf88bb11

	column Comuna_Cod
		dataType: int64
		formatString: 0
		lineageTag: f7eeab90-73ed-41cd-bb0f-6c7558093844
		summarizeBy: none
		sourceColumn: Comuna_Cod

		annotation SummarizationSetBy = Automatic

	column SATC_Cantidad
		dataType: int64
		formatString: 0
		lineageTag: 9ec51e4a-f7f3-4a8b-866c-8c49d7bac4be
		summarizeBy: sum
		sourceColumn: SATC_Cantidad

		annotation SummarizationSetBy = Automatic

	partition Dim_SATC_Relaciones = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\santi\OneDrive\Escritorio\Chamba\Dashboard\data\model\Modelo_Reporte_Paginas_2026.xlsx"), null, true),
				    Dim_SATC_Relaciones_Sheet = Origen{[Item="Dim_SATC_Relaciones",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(Dim_SATC_Relaciones_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Comuna_Cod", Int64.Type}, {"SATC_Cantidad", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Exception

